language: node_js
node_js:
  - stable
  - lts/erbium
  - lts/dubnium

before_script:
  - npm install --global coveralls
script:
  - npm test -- --coverage
after_script:
  - cat coverage/lcov.info | coveralls
